services:

  openvas-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ov1-service
    env_file:
      - .env
    ports:
      - "8081:8081"
    restart: unless-stopped
    volumes:
      - greenbone-community-edition_gvmd_socket_vol:/run/gvmd
      - ./gsa_key.json:/run/secrets/gsa_key.json:ro

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: ov1-jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  greenbone-community-edition_gvmd_socket_vol:
    external: true
  jenkins_home:
    driver: local