services:
  openvas-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ov1-service
    env_file:
      - .env
    ports:
      - "8081:8081"
    restart: unless-stopped
    volumes:
      - greenbone-community-edition_gvmd_socket_vol:/run/gvmd

volumes:
  greenbone-community-edition_gvmd_socket_vol:
    external: true